name: Deploy website
on:
  push:
  # Event
  pull_request:

		# We can define Activity Type like this by using the `types` key. The is key name has to be types.
    types: opened

    # Also like this
		# types:[opened, edited]

    # Also like this
		# types:
		# - opened
		# - edited

    # Also like this
		# types:
		# - opened

	# Event. We still have to write it like below even though we do not provide any values for the workflow_dispatch event
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
